### ISSUE TITLE
java.lang.IllegalStateException: You cannot access the Navigator’s state until the Navigator is attached

### ISSUE THREAD

**Issue by FunkyMuse** [eygraber/compose-material3-navigation#5]
java.lang.IllegalStateException: You cannot access the Navigator’s state until the Navigator is attached

https://github.com/eygraber/compose-material3-navigation/blob/21a20f06cd09844f76545dc24a3741acb3ca9731/library/src/androidMain/kotlin/com/eygraber/compose/material3/navigation/ModalBottomSheetNavigator.android.kt#L25

Usage:

![image](https://github.com/user-attachments/assets/477070f6-7936-45e3-b5f3-7dd6d472ff1b)

```kotlin
@Composable
private fun backStackNavEntryController(navHostController: NavHostController): Triple<NavBackStackEntry?, NavBackStackEntry?, Boolean> {
    val currentEntry by navHostController.currentBackStackEntryFlow.collectAsStateWithLifecycle(
        null
    )

    val previousEntry by remember(currentEntry) {
        derivedStateOf {
            navHostController.previousBackStackEntry
        }
    }

    val hideBottomNavigation by remember(currentEntry) {
        derivedStateOf {
            currentEntry.hideBottomNavigation
        }
    }
    return Triple(currentEntry, previousEntry, hideBottomNavigation)
}
```

**Comment by eygraber** [comment]
The issue is that `Scaffold` uses `SubcomposeLayout` which causes the `NavHost` to get composed after a slight delay, which also delays the `ModalBottomSheetNavigator` from getting fully attached. 

Then `backStackNavEntryController` accesses the navigator's state before it is ready, causing the crash. The issue is fixed if `ModalBottomSheetLayout` is moved inside the `Scaffold` content.

I'll add some documentation to `ModalBottomSheetLayout` to indicate that `NavHost` should be called directly in its composition.

**Comment by FunkyMuse** [comment]
Thanks, but Ppeviously i've used the Androidx Material navigation without a problem in this regard, why should this now be an issue?

**Comment by eygraber** [comment]
Interesting, I based my implementation on `dialog` destinations, which is built in to `NavHost` so they don't have to worry about this issue.

I looked into the [Androidx Material navigation implementation](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material-navigation/src/main/java/androidx/compose/material/navigation/BottomSheetNavigator.kt;l=110) and they guard against these conditions.

I should probably do something similar.

**Comment by eygraber** [comment]
It guards against it in the sense that it won't crash. I guess `ModalBottomSheet` doesn't work so well with `SubComposeLayout` in this scenario.
