### ISSUE TITLE
Long bottom sheet doesn't reach expanded and it's glitchy on drag

### ISSUE THREAD

**Issue by FunkyMuse** [eygraber/compose-material3-navigation#7]
[Screen_recording_20241118_010215.webm](https://github.com/user-attachments/assets/ac71667e-110d-4b35-80ee-3532ecd9359c)

```kotlin
bottomSheet<WhyINeedAnAccountScreen> {
        WhyINeedAnAccountScreen()
    }
```

```kotlin
@Composable
internal fun WhyINeedAnAccountScreen() {
    Column {
        Spacer(Modifier.padding(vertical = MaterialTheme.dimens.padding.large))

        Text(
            text = stringResource(Res.string.why_do_i_need_to_sign_in),
            modifier = Modifier
                .fillMaxWidth()
                .padding(
                    vertical = MaterialTheme.dimens.padding.large,
                    horizontal = MaterialTheme.dimens.padding.xxxL
                ),
            style = MaterialTheme.typography.headlineMedium
        )

        Spacer(Modifier.padding(vertical = MaterialTheme.dimens.padding.xL))

        WhyDoINeedAnAccountItem(
            title = stringResource(Res.string.why_do_i_need_acc_anti_piracy_title),
            text = stringResource(
                Res.string.why_do_i_need_acc_anti_piracy_explanation,
                if (isAndroid) stringResource(Res.string.google_title) else stringResource(Res.string.apple_title)
            ),
            icon = Icons.Default.Shield
        )

......

}
```

**Comment by eygraber** [comment]
It's likely because I made the default `contentWindowInsets` optimized for edge to edge drawing. Does it work better if you set it to the `ModalBottomSheet` default?

```kotlin
ModalBottomSheetLayout(
  ...,
  contentWindowInsets = {
    WindowInsets.safeDrawing.only(WindowInsetsSides.Bottom)
  }
)
```

**Comment by FunkyMuse** [comment]
> It's likely because I made the default `contentWindowInsets` optimized for edge to edge drawing. Does it work better if you set it to the `ModalBottomSheet` default?
> 
> ```kotlin
> ModalBottomSheetLayout(
>   ...,
>   contentWindowInsets = {
>     WindowInsets.safeDrawing.only(WindowInsetsSides.Bottom)
>   }
> )
> ```

It works better but i'm not sure if whether this is the right place to add a global contentWindowInsets, since some bottom sheets should have different insents than others, i think it's a bad API design and this should be driven by the `bottomSheet` composable for creating the content.

Apart from that I think the `bottomSheet` should have `onDismissRequest` as a callback in order to know when one is dismissed, I miss that in dialog too and in `bottomSheet`

**Comment by eygraber** [comment]
@FunkyMuse agreed. I still want to think a little more about `onDismissRequest` though, maybe that should be using the navigation APIs instead?

**Comment by FunkyMuse** [comment]
> @FunkyMuse agreed. I still want to think a little more about `onDismissRequest` though, maybe that should be using the navigation APIs instead?

For example each destination that lives in the `navigation<>` lambda of a graph has a `bottomSheet<>`

Now sometimes I want to know when the bottomSheet is dismissed to call an action, currently with this API, there's no callback if a user dismissed the bottomSheet by just swiping it down

**Comment by eygraber** [comment]
Can't you observe the navigation backstack, or current entry?
